@startuml AccountServiceClass

class AccountServices {
    + AccountServices(IConfiguration)
    + CreateToken(Account)
    + IsValidEmail(string)
    + CreatePasswordHash(string, out byte[], out byte[])
    + TryVerifyPasswordHash(string, byte[], byte[])

    }


@enduml