@startuml AccountChangeEmail 


Actor "User" as U
participant "Frontend" as F
participant "Account" as A
participant "AccountService" as S
participant "DataContext" as D
mainframe **Epic 1, US4:** Ændre Email 


U -> F : ChangeEmail
activate F
F -> A : ChangeEmail(AccountChangeEmailDto)
deactivate F 
activate A
A -> S : Where(x => x.Email == request.Email)
activate S
S -> D : Where(x => x.Email == request.Email)
activate D

alt Email not found
    D -->> S : false
    deactivate D
    S -->> A : false
    deactivate S
    A -->> F : NotFound(Email)
else 
    activate S
    activate D
    D -->> S : Account
    deactivate D
    S -->> A : Account
    deactivate S

    A -> S : TryVerifyPasswordHash(Password,PasswordHash,PasswordSalt)

    alt Password does not match
        activate S
        S -->> A: false
        deactivate S
        A -->> F : BadRequest("Not a valid Password")
    else 
        activate S
        S -->> A : true
        deactivate S
        
        A -> S : SaveChangesAsync()
        activate S 
        S -> D : SaveChangesAsync()
        activate D
        D -->> S : ok
        deactivate D
        S -->> A : ok
        deactivate S
        A -->> F : Accepted(Account)
        deactivate A 
    end
end

@enduml