@startuml AccountChangePassword
mainframe **Epic 1, US5:** Ændre Password


Actor "User" as U
participant "Frontend" as F
participant "Account" as A
participant "AccountService" as S
participant "DataContext" as D



U -> F : ChangePassword
activate F 
F -> A : ChangePassword(AccountChangePasswordDto)
deactivate F 
activate A
A -> S : FirstOrDefaultAsync(x => x.Email == request.Email)
activate S
S -> D : FirstOrDefaultAsync(x => x.Email == request.Email)
activate D

alt Email not found
    D -->> S : false
    deactivate D
    S -->> A : false
    deactivate S
    A -->> F : NotFound(Email)
else 
    activate S
    activate D
    D -->> S : Account
    deactivate D
    S -->> A : Account
    deactivate S
    A -> S : TryVerifyPasswordHash(Password,PasswordHash,PasswordSalt)
    alt Password does not match
        activate S
        S -->> A: false
        deactivate S
        A -->> F : BadRequest("Not a valid Password")
    else 
        activate S
        S -->> A : true
        deactivate S
        
        A -> S : CreatePasswordHash(NewPassword,PasswordHash,PasswordSalt)
        activate S
        S -->> A : Password, PasswordHash, PasswordSalt
        deactivate S 
        A -> S : SaveChangesAsync()
        activate S
        S -> D : SaveChangesAsync()
        activate D
        D -->> S : ok 
        deactivate D
        S -->> A : ok
        deactivate S
        A -> S : CreateToken(Account)
        activate S
        S -->> A : JWT Token
        deactivate S
        A -->> F : Ok(JWT Token)
        deactivate A
    end
end
@enduml