@startuml AccountChangePassword

Actor "User" as U
participant "Frontend" as F
participant "Account" as A
participant "AccountService" as S
participant "DataContex" as D



U -> F : ChangePassword
activate F 
F -> A : ChangePassword(AccountChangePasswordDto)
deactivate F 
activate A
A -> S : FirstOrDefaultAsync(x => x.Email == request.Email)
activate S
S -> D : FirstOrDefaultAsync(x => x.Email == request.Email)
activate D
D --> S : Account
deactivate D
S --> A : Account
deactivate S
A -> S : TryVerifyPassword(Password,PasswordHash,PasswordSalt)
activate S
S --> A : true 
deactivate S
A -> S : CreatePasswordHash(NewPassword,PasswordHash,PasswordSalt)
activate S
S --> A : Password, PasswordHash, PasswordSalt
deactivate S 
A -> S : SaveChangesAsync()
activate S
S -> D : SaveChangesAsync()
activate D
D --> S : ok 
deactivate D
S --> A : ok
deactivate S
A -> S : CreateToken(Account)
activate S
S --> A : JWT Token
deactivate S
A --> F : JWT Token
deactivate A


@enduml