@startuml
' !theme carbon-gray
' !theme plain
' !theme aws-orange
!theme materia
hide circle
'hide members
'hide fields

class Account {
    I d
    Name
    Weight
    Gender
    Age
    Email
    Password
}

Class Workout{
    I d
    Duration
    Intensity
}

Class Exercise {
    I d
    Category
    Duration
    Intensity
    Repetitions
    Set
    Pictures 
    Video
}


class Milestone {
    I d
    Category
    Goal
    StartDate
    EndDate
}

class Meal {
    I d
    Category
    Description
    NutritunalValue
}

class Dish {
    I d
    Category
    NutritunalValue 
    Recipe
    Ingredients
    Picture
}

class Calender {
    I d
    List<Workout, Date>
    List<Meal, Date>
}




Account "1" -l- "0..*" Workout : Creates
Account "1" -r- "0..*" Meal : Creates
Account "1" -- "0..*" Milestone : Creates
Workout"1" -- "1..*" Exercise : Consists of  
Meal"1" -- "1..*" Dish : Consists of  
Account "1" -u- "1" Calender : Has a


Calender "1" -- "0..*" Workout : Shows
Calender "1" --  "0..*" Meal : Shows
@enduml