@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/react.puml
!include DEVICONS/java.puml
!include DEVICONS/mongodb.puml
!include FONTAWESOME/users.puml

AddElementTag("storage", $shape=RoundedBoxShape(), $bgColor="lightSkyBlue", $fontColor="white")

Person(user, "Users", "The users of the system", $sprite="users")
System_Boundary(c1, "FATT") {
    Container(Web_api, "Web Api", "C#, ASP.NET Core 6 Web API", "Data Acess to MongoDB ", $sprite="")
    ContainerDb(db, "Database", "MongoDB, NoSQL", "Holds product, order and invoice information", $sprite="mongodb", $tag="storage")
    Container(Web_app, "Web application", "React, Javasprict, Client", $sprite="react")
    
}


Rel(Web_api, db, "Reads/Writes to", "JSON")
Rel(Web_app, Web_api, "Make API Calls", "JSON")
Rel(user, Web_app, "Interract", "HTTPS")

SHOW_LEGEND()

@enduml